export const permissions = [
  "organisation.settings.read",
  "organisation.settings.update",
  "organisation.member.manage",
  "organisation.service.manage",
  "people.read",
  "people.create",
  "people.update",
  "people.archive",
  "people.import",
  "people.export",
  "crm.lead.read",
  "crm.lead.create",
  "crm.lead.update",
  "crm.lead.assign",
  "crm.lead.convert",
  "finance.invoice.read",
  "finance.invoice.manage",
  "finance.payment.read",
  "finance.payment.create",
  "finance.payment.refund",
  "finance.expense.manage",
  "payroll.employee.read",
  "payroll.employee.manage",
  "payroll.salary.view",
  "payroll.run.prepare",
  "payroll.run.approve",
  "payroll.run.markPaid",
  "inventory.product.read",
  "inventory.product.manage",
  "inventory.stock.manage",
  "inventory.negativeStock.override",
  "audit.read",
] as const;

export type Permission = (typeof permissions)[number];

