CREATE ROLE crmkaro_owner LOGIN PASSWORD 'crmkaro_owner_local_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE crmkaro_app LOGIN PASSWORD 'crmkaro_app_local_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

CREATE DATABASE crmkaro OWNER crmkaro_owner;

\connect crmkaro

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO crmkaro_app;

ALTER DEFAULT PRIVILEGES FOR ROLE crmkaro_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crmkaro_app;

ALTER DEFAULT PRIVILEGES FOR ROLE crmkaro_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO crmkaro_app;

