import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  TextInput,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Linking,
  Alert,
  RefreshControl,
} from "react-native";
import { AppHeader } from "../../components/AppHeader";
import { StatCard } from "../../components/StatCard";
import { Badge } from "../../components/Badge";
import { BottomSheet } from "../../components/BottomSheet";
import { PrimaryButton } from "../../components/PrimaryButton";
import { Icon } from "../../components/Icon";
import { apiFetch } from "../../api/client";
import { useAuth } from "../../context/AuthContext";
import { colors, radius, spacing } from "../../theme/colors";

type Invoice = {
  id: string;
  invoiceNumber: string;
  issueDate: string;
  dueDate: string | null;
  status: "DRAFT" | "ISSUED" | "PARTIALLY_PAID" | "PAID" | "VOID";
  totalMinor: number;
  balanceDueMinor: number;
  person?: { displayName: string; primaryPhone?: string | null };
  items?: Array<{ description: string; quantity: number; unitPriceMinor: number }>;
};

export function FinanceScreen() {
  const { activeOrg } = useAuth();
  const [activeTab, setActiveTab] = useState<"invoices" | "expenses">("invoices");
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  // Create Invoice Modal State
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [people, setPeople] = useState<Array<{ id: string; displayName: string }>>([]);
  const [selectedPersonId, setSelectedPersonId] = useState("");
  const [itemDesc, setItemDesc] = useState("Academic Tuition Fees");
  const [itemPrice, setItemPrice] = useState("2500");
  const [createBusy, setCreateBusy] = useState(false);

  // Share Bill Modal
  const [shareInvoice, setShareInvoice] = useState<Invoice | null>(null);

  const fetchFinanceData = useCallback(async () => {
    try {
      const [invRes, peopleRes] = await Promise.all([
        apiFetch<{ items: Invoice[] }>("/finance/invoices?limit=50"),
        apiFetch<{ items: Array<{ id: string; displayName: string }> }>("/people?limit=100"),
      ]);

      if (invRes.data?.items) {
        setInvoices(invRes.data.items);
      }
      if (peopleRes.data?.items) {
        setPeople(peopleRes.data.items);
        if (peopleRes.data.items[0]) {
          setSelectedPersonId(peopleRes.data.items[0].id);
        }
      }
    } catch {}
    finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchFinanceData();
  }, [fetchFinanceData]);

  const handleCreateInvoice = async () => {
    if (!selectedPersonId) {
      Alert.alert("Required", "Please select a member.");
      return;
    }
    const num = Number(itemPrice);
    if (!num || num <= 0) {
      Alert.alert("Required", "Please enter a valid item price.");
      return;
    }

    setCreateBusy(true);
    try {
      const res = await apiFetch("/finance/invoices", {
        method: "POST",
        body: JSON.stringify({
          personId: selectedPersonId,
          issueDate: new Date().toISOString(),
          items: [
            {
              description: itemDesc.trim() || "Service Fees",
              quantity: 1,
              unitPriceMinor: Math.round(num * 100),
            },
          ],
        }),
      });

      if (res.error) throw new Error(res.error);

      setIsCreateOpen(false);
      fetchFinanceData();
    } catch (err: any) {
      Alert.alert("Error", err.message || "Failed to create invoice.");
    } finally {
      setCreateBusy(false);
    }
  };

  const shareViaWhatsApp = (inv: Invoice) => {
    const orgName = activeOrg?.name || "CRMKaro";
    const amountStr = `₹${(inv.totalMinor / 100).toLocaleString("en-IN")}`;
    const name = inv.person?.displayName || "Student / Customer";
    const msg = `Hello ${name},\n\nYour Fee Invoice #${inv.invoiceNumber} for ${amountStr} has been generated by ${orgName}.\n\nStatus: ${inv.status}\n\nPlease complete the payment at your earliest convenience.\n\nThank you!`;

    const phone = inv.person?.primaryPhone?.replace(/\D/g, "");
    if (phone) {
      Linking.openURL(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`);
    } else {
      Linking.openURL(`whatsapp://send?text=${encodeURIComponent(msg)}`);
    }
    setShareInvoice(null);
  };

  const formatRupees = (minor = 0) => `₹${(minor / 100).toLocaleString("en-IN")}`;

  const totalCollected = invoices
    .filter((i) => i.status === "PAID")
    .reduce((sum, i) => sum + i.totalMinor, 0);

  const totalOutstanding = invoices
    .filter((i) => i.status !== "PAID" && i.status !== "VOID")
    .reduce((sum, i) => sum + i.balanceDueMinor, 0);

  return (
    <View style={styles.container}>
      <AppHeader
        title="Finance & Invoices"
        subtitle="Billing, receipts and financial ledger"
        rightAction={
          <TouchableOpacity
            onPress={() => setIsCreateOpen(true)}
            style={styles.addBtn}
          >
            <Icon name="Plus" size={18} color="#ffffff" />
          </TouchableOpacity>
        }
      />

      <FlatList
        data={invoices}
        keyExtractor={(item) => item.id}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => {
              setRefreshing(true);
              fetchFinanceData();
            }}
          />
        }
        contentContainerStyle={styles.list}
        ListHeaderComponent={
          <>
            {/* Quick Metrics */}
            <View style={styles.metricsRow}>
              <View style={styles.metricCol}>
                <StatCard
                  label="Total Invoiced"
                  value={formatRupees(totalCollected + totalOutstanding)}
                  tone="blue"
                />
              </View>
              <View style={styles.metricCol}>
                <StatCard
                  label="Pending Dues"
                  value={formatRupees(totalOutstanding)}
                  tone="rose"
                />
              </View>
            </View>

            {/* Invoices List Header */}
            <View style={styles.listHeaderRow}>
              <Text style={styles.sectionTitle}>Invoices Ledger ({invoices.length})</Text>
            </View>
          </>
        }
        renderItem={({ item }) => (
          <View style={styles.invoiceCard}>
            <View style={styles.invoiceMain}>
              <View style={styles.invoiceTopRow}>
                <Text style={styles.invoiceNumber}>{item.invoiceNumber}</Text>
                <Badge tone={item.status === "PAID" ? "emerald" : "amber"}>
                  {item.status}
                </Badge>
              </View>
              <Text style={styles.payerName}>{item.person?.displayName || "Member"}</Text>
              <Text style={styles.invoiceDate}>
                Issued: {new Date(item.issueDate).toLocaleDateString("en-IN")}
              </Text>
            </View>

            <View style={styles.invoiceRight}>
              <Text style={styles.invoiceAmount}>{formatRupees(item.totalMinor)}</Text>
              <TouchableOpacity
                onPress={() => setShareInvoice(item)}
                style={styles.shareBtn}
              >
                <Icon name="MessageSquare" size={13} color={colors.emerald} />
                <Text style={styles.shareBtnText}>Share</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}
      />

      {/* Create Invoice BottomSheet */}
      <BottomSheet
        visible={isCreateOpen}
        onClose={() => setIsCreateOpen(false)}
        title="Create Fee Invoice"
        subtitle="Generate a new bill for member or student"
        footer={
          <View style={styles.modalFooterRow}>
            <PrimaryButton
              title="Cancel"
              onPress={() => setIsCreateOpen(false)}
              variant="outline"
              style={{ flex: 1 }}
            />
            <PrimaryButton
              title={createBusy ? "Creating…" : "Generate Invoice"}
              onPress={handleCreateInvoice}
              loading={createBusy}
              style={{ flex: 1 }}
            />
          </View>
        }
      >
        <View style={styles.formWrap}>
          <Text style={styles.label}>Select Member *</Text>
          <View style={styles.peopleSelector}>
            {people.slice(0, 8).map((p) => (
              <TouchableOpacity
                key={p.id}
                onPress={() => setSelectedPersonId(p.id)}
                style={[
                  styles.personChip,
                  selectedPersonId === p.id && styles.personChipActive,
                ]}
              >
                <Text
                  style={[
                    styles.personChipText,
                    selectedPersonId === p.id && styles.personChipTextActive,
                  ]}
                >
                  {p.displayName}
                </Text>
              </TouchableOpacity>
            ))}
          </View>

          <Text style={[styles.label, { marginTop: spacing.md }]}>Fee Description *</Text>
          <TextInput
            style={styles.input}
            value={itemDesc}
            onChangeText={setItemDesc}
            placeholder="e.g. Monthly Tuition Fees"
          />

          <Text style={[styles.label, { marginTop: spacing.md }]}>Amount (₹) *</Text>
          <TextInput
            style={styles.input}
            value={itemPrice}
            onChangeText={setItemPrice}
            keyboardType="numeric"
            placeholder="2500"
          />
        </View>
      </BottomSheet>

      {/* Share Invoice BottomSheet */}
      {Boolean(shareInvoice) && (
        <BottomSheet
          visible={Boolean(shareInvoice)}
          onClose={() => setShareInvoice(null)}
          title="Share Fee Receipt"
          subtitle={`Bill #${shareInvoice?.invoiceNumber} for ${shareInvoice?.person?.displayName}`}
          footer={
            <PrimaryButton
              title="Share on WhatsApp"
              onPress={() => shareViaWhatsApp(shareInvoice!)}
              variant="emerald"
              icon={<Icon name="MessageSquare" size={16} color="#ffffff" />}
            />
          }
        >
          <View style={styles.receiptPreview}>
            <Text style={styles.receiptText}>
              {`Invoice #${shareInvoice?.invoiceNumber}\nCustomer: ${shareInvoice?.person?.displayName}\nAmount: ${formatRupees(shareInvoice?.totalMinor)}\nStatus: ${shareInvoice?.status}\nDate: ${new Date(shareInvoice?.issueDate || "").toLocaleDateString("en-IN")}`}
            </Text>
          </View>
        </BottomSheet>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  addBtn: {
    width: 34,
    height: 34,
    borderRadius: radius.pill,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  list: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
  },
  metricsRow: {
    flexDirection: "row",
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  metricCol: {
    flex: 1,
  },
  listHeaderRow: {
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.ink,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  invoiceCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    marginBottom: spacing.xs,
  },
  invoiceMain: {
    flex: 1,
  },
  invoiceTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  invoiceNumber: {
    fontSize: 13.5,
    fontWeight: "700",
    color: colors.ink,
  },
  payerName: {
    fontSize: 12.5,
    fontWeight: "600",
    color: colors.inkSecondary,
    marginTop: 2,
  },
  invoiceDate: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 2,
  },
  invoiceRight: {
    alignItems: "flex-end",
    gap: 6,
  },
  invoiceAmount: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.emerald,
  },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.emeraldLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
  },
  shareBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.emerald,
  },
  modalFooterRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  formWrap: {
    gap: spacing.xs,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.inkSecondary,
  },
  peopleSelector: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  personChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceMuted,
  },
  personChipActive: {
    backgroundColor: colors.brandLight,
    borderColor: colors.brand,
  },
  personChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.muted,
  },
  personChipTextActive: {
    color: colors.brand,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    height: 42,
    fontSize: 13.5,
    color: colors.ink,
  },
  receiptPreview: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
  },
  receiptText: {
    fontFamily: "monospace",
    fontSize: 12.5,
    color: colors.ink,
    lineHeight: 20,
  },
});
